### PR TITLE
Fix typos in documentation

### PR DESCRIPTION
**Pull request by paultcochrane**
While reading through the README I noticed a couple of typos.  These have been fixed in the README and the POD in this PR.  If you're not happy with this PR and want something changed, please just let me know and I'll update as appropriate and resubmit.

### CODE REVIEW

**Comment by exodist** [comment]
I am pretty short on time to devote to this module. I have added you as a colaberator, go ahead and merge your improvements. If you give me your PAUSE id I will give you upload permissions as well.

**Comment by exodist** [comment]
I am not too picky for this module, I have been neglecting it, and it is not at all a priority for me. You now have co-maint on cpan.

**Comment by paultcochrane** [comment]
Just as a quick question: would you be able to link this repo to Travis and AppVeyor?  Don't know if you have accounts on those services, but if you do, that'd be very helpful for two of the PRs I've got in the pipeline.  If it's too much work, don't worry about it, I'll see if I can link things up another way.

**Comment by exodist** [comment]
I went to enable it and it looks like github is deprecating the use of services, do you know what the correct way to add it is now?

**Comment by paultcochrane** [comment]
It's been a while since I did it, but I think services aren't needed, and that one just needs to give Travis read access to your GitHub repos.  IIRC, one logs in to Travis (the GitHub credentials should work here) and then goes to https://travis-ci.org/profile/<github-username> where you can then sync your repos.  You should get asked at some point by GitHub if Travis should be allowed access to your repos, and once accepted, the sync process should "just work" (ahem).  Once that's done, you just flick the switch on the relevant repo and a build will take place the next time someone pushes to the repo.  You can see which applications are allowed to access your GitHub account at https://github.com/settings/applications.  Hope that makes sense!

**Comment by paultcochrane** [comment]
Another option would be if you give me admin privs on your repo, then I can link to Travis via my account.  Just a thought; I can understand if that's going too far for you.

**Pull request merged**
